# Generated by Django 6.1.1 on 2026-09-06 08:24

import django.core.validators
import django.db.models.functions.text
import household.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('next_due_date', models.DateField(default=household.models.household_local_date)),
                ('is_active', models.BooleanField(default=True)),
                ('completion_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='unique_active_chore_name_ci'), models.CheckConstraint(condition=models.Q(('frequency_days__gte', 1), ('frequency_days__lte', 365)), name='chore_frequency_days_range'), models.CheckConstraint(condition=models.Q(('points__gte', 1), ('points__lte', 100)), name='chore_points_range'), models.CheckConstraint(condition=models.Q(('completion_version__gte', 0)), name='chore_completion_version_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('display_order',),
                'constraints': [models.CheckConstraint(condition=models.Q(('display_order__gte', 1)), name='member_display_order_positive')],
            },
        ),
    ]
