# Generated by Django 6.1.1 on 2026-09-06 08:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('awarded_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('chore_name_snapshot', models.CharField(max_length=100)),
                ('completed_version', models.PositiveIntegerField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='household.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='household.member')),
            ],
            options={
                'ordering': ('-completed_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('awarded_points__gte', 1), ('awarded_points__lte', 100)), name='completion_awarded_points_range'), models.CheckConstraint(condition=models.Q(('chore_name_snapshot', ''), _negated=True), name='completion_chore_name_snapshot_nonempty'), models.CheckConstraint(condition=models.Q(('completed_version__gte', 0)), name='completion_version_nonnegative'), models.UniqueConstraint(fields=('chore', 'completed_version'), name='unique_chore_completed_version')],
            },
        ),
    ]
