import { api } from './api.js';

let state;
let view = 'shopping';
const app = document.querySelector('#app');
const modalRoot = document.querySelector('#modal-root');
const euro = new Intl.NumberFormat('en-DE', { style: 'currency', currency: 'EUR' });
const date = (value) => new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`));
const member = (id) => state.members.find((entry) => entry.id === id);
const avatar = (id) => `<span class="avatar avatar-${member(id).color}">${member(id).name[0]}</span>`;
const allIds = () => state.members.map((m) => m.id);

function balances() {
  const net = Object.fromEntries(allIds().map((id) => [id, 0]));
  state.expenses.forEach((expense) => { const share = expense.amount / expense.participants.length; net[expense.paidBy] += expense.amount; expense.participants.forEach((id) => { net[id] -= share; }); });
  const debtors = Object.entries(net).filter(([, value]) => value < -0.005).map(([id, value]) => ({ id, amount: -value }));
  const creditors = Object.entries(net).filter(([, value]) => value > 0.005).map(([id, value]) => ({ id, amount: value }));
  const debts = [];
  while (debtors.length && creditors.length) { const debtor = debtors[0], creditor = creditors[0], amount = Math.min(debtor.amount, creditor.amount); debts.push({ from: debtor.id, to: creditor.id, amount }); debtor.amount -= amount; creditor.amount -= amount; if (debtor.amount < .005) debtors.shift(); if (creditor.amount < .005) creditors.shift(); }
  const settled = new Set(state.settlements.map((entry) => `${entry.from}:${entry.to}`));
  return { net, debts: debts.filter((d) => !settled.has(`${d.from}:${d.to}`)) };
}
function header(eyebrow, title, action = '') { return `<header class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div>${action}</header>`; }
function renderShopping() {
  const items = state.shopping.map((item) => `<li class="shopping-item"><span class="check-circle"></span><div><strong>${escapeHtml(item.name)}</strong><small>Added by ${member(item.addedBy).name}</small></div><button class="buy-button" data-buy="${item.id}">Mark as bought <span>→</span></button></li>`).join('') || `<li class="empty"><span>✓</span><strong>Everything is sorted</strong><p>Add something when the household needs it.</p></li>`;
  app.innerHTML = `${header('ELM STREET HOME', 'Shopping list', '<button class="primary" data-open="add-item">+ Add item</button>')}<section class="intro-card"><div><span class="spark">✦</span><strong>Need it? Add it. Bought it? Share it.</strong><p>Mark an item as bought and it becomes a shared expense automatically.</p></div></section><section class="list-card"><div class="card-label"><span>TO PICK UP</span><span>${state.shopping.length} item${state.shopping.length === 1 ? '' : 's'}</span></div><ul class="shopping-list">${items}</ul></section>`;
}
function renderExpenses() {
  const expenses = state.expenses.map((expense) => { const isMine = expense.paidBy === state.currentUserId; const names = expense.participants.map((id) => member(id).name).join(', '); return `<li class="expense-row"><div class="expense-icon">${expense.source === 'shopping' ? '⌑' : '€'}</div><div class="expense-info"><strong>${escapeHtml(expense.name)}</strong><small>Paid by ${member(expense.paidBy).name} · Split with ${names}</small></div><div class="expense-amount"><strong>${euro.format(expense.amount)}</strong><small>${date(expense.createdAt)}</small></div>${isMine ? `<div class="row-actions"><button data-edit="${expense.id}" aria-label="Edit">✎</button><button data-delete="${expense.id}" aria-label="Delete">×</button></div>` : '<span class="locked">Shared</span>'}</li>`; }).join('') || '<li class="empty"><strong>No expenses yet</strong><p>Expenses from bought items will appear here.</p></li>';
  app.innerHTML = `${header('SHARED TAB', 'Expenses', '<button class="primary" data-open="add-expense">+ Add expense</button>')}<section class="summary-strip"><div><span>Total tracked</span><strong>${euro.format(state.expenses.reduce((sum, e) => sum + e.amount, 0))}</strong></div><div><span>Your paid total</span><strong>${euro.format(state.expenses.filter((e) => e.paidBy === state.currentUserId).reduce((sum, e) => sum + e.amount, 0))}</strong></div><p>Only expenses you created can be edited or deleted.</p></section><section class="list-card"><div class="card-label"><span>ALL EXPENSES</span><span>${state.expenses.length} entries</span></div><ul class="expense-list">${expenses}</ul></section>`;
}
function renderBalances() { const { net, debts } = balances(); const members = state.members.map((m) => `<li class="balance-member">${avatar(m.id)}<strong>${m.name}${m.id === state.currentUserId ? ' <small>(you)</small>' : ''}</strong><span class="${net[m.id] >= 0 ? 'positive' : 'negative'}">${net[m.id] >= 0 ? '+' : '−'}${euro.format(Math.abs(net[m.id]))}</span></li>`).join(''); const debtsHtml = debts.map((debt) => `<li class="debt-row">${avatar(debt.from)}<div><strong>${member(debt.from).name} owes ${member(debt.to).name}</strong><small>${euro.format(debt.amount)} to settle up</small></div>${avatar(debt.to)}<button class="settle" data-settle="${debt.from}:${debt.to}">Mark settled</button></li>`).join('') || `<li class="empty"><span>✦</span><strong>All settled up</strong><p>There are no outstanding debts.</p></li>`; app.innerHTML = `${header('WHO OWES WHAT', 'Balances')}<section class="balance-grid"><article class="list-card"><div class="card-label"><span>NET BALANCE</span><span>Across all expenses</span></div><ul class="member-list">${members}</ul></article><article class="balance-note"><span>↗</span><strong>Positive means they are owed money.</strong><p>Negative means they owe the household.</p></article></section><section class="list-card debts"><div class="card-label"><span>PAIRWISE DEBTS</span><span>${debts.length} to settle</span></div><ul class="debt-list">${debtsHtml}</ul></section>`; }
function renderHousehold() { const people = state.members.map((m) => `<li class="person-row">${avatar(m.id)}<div><strong>${m.name}${m.id === state.currentUserId ? ' <small>(you)</small>' : ''}</strong><small>${m.id === state.currentUserId ? 'Household member' : 'Household member'}</small></div></li>`).join(''); app.innerHTML = `${header('YOUR SHARED SPACE', 'Elm Street Home')}<section class="household-grid"><article class="list-card"><div class="card-label"><span>MEMBERS</span><span>${state.members.length} people</span></div><ul class="person-list">${people}</ul></article><article class="invite-card"><span class="spark">✦</span><h2>Invite someone home</h2><p>Share this code so they can join your household.</p><div class="invite-code"><strong>${state.household.inviteCode}</strong><button data-copy="${state.household.inviteLink}">Copy link</button></div></article></section>`; }
function render() { document.querySelectorAll('.nav-link').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); document.querySelector('#shopping-count').textContent = state.shopping.length; ({ shopping: renderShopping, expenses: renderExpenses, balances: renderBalances, household: renderHousehold })[view](); }
function escapeHtml(value) { const node = document.createElement('div'); node.textContent = value; return node.innerHTML; }
function modal(title, content) { modalRoot.innerHTML = `<div class="backdrop" data-close><section class="modal" role="dialog" aria-modal="true" aria-label="${title}" onclick="event.stopPropagation()"><button class="modal-close" data-close aria-label="Close">×</button><h2>${title}</h2>${content}</section></div>`; }
function closeModal() { modalRoot.innerHTML = ''; }
function addItemModal() { modal('Add to the list', `<p>What does the household need?</p><form id="add-item-form"><label>Item name<input autofocus name="name" placeholder="e.g. Kitchen roll" required maxlength="60"></label><button class="primary wide">Add item</button></form>`); }
function participantInputs(selected = allIds()) { return state.members.map((m) => `<label class="participant"><input type="checkbox" name="participants" value="${m.id}" ${selected.includes(m.id) ? 'checked' : ''}><span>${avatar(m.id)} ${m.name}${m.id === state.currentUserId ? ' (you)' : ''}</span></label>`).join(''); }
function expenseModal(expense = null) { const editing = !!expense; modal(editing ? 'Edit expense' : 'Add an expense', `<p>${editing ? 'Update an expense you created.' : 'Add a shared cost directly to the tab.'}</p><form id="expense-form" data-id="${expense?.id || ''}"><label>Description<input autofocus name="name" value="${expense ? escapeHtml(expense.name) : ''}" placeholder="e.g. Cleaning supplies" required maxlength="60"></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" value="${expense?.amount || ''}" placeholder="0.00" required></label><fieldset><legend>Split between</legend><div class="participant-grid">${participantInputs(expense?.participants)}</div></fieldset><button class="primary wide">${editing ? 'Save changes' : 'Add expense'}</button></form>`); }
function buyModal(item) { modal(`Bought ${escapeHtml(item.name)}?`, `<p>Enter what you paid. This removes it from the list and creates a shared expense split with everyone.</p><form id="buy-form" data-id="${item.id}"><label>Price paid<input autofocus name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" required></label><button class="primary wide">Add to shared tab</button></form>`); }
function toast(message) { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); }
async function refresh(nextState, message) { state = nextState; closeModal(); render(); if (message) toast(message); }

document.querySelector('#nav').addEventListener('click', (event) => { const button = event.target.closest('[data-view]'); if (button) { view = button.dataset.view; render(); } });
document.querySelector('#reset-demo').addEventListener('click', async () => refresh(await api.reset(), 'Demo data reset'));
document.addEventListener('click', async (event) => { const target = event.target.closest('button, .backdrop'); if (!target) return; if (target.dataset.close !== undefined) closeModal(); if (target.dataset.open === 'add-item') addItemModal(); if (target.dataset.open === 'add-expense') expenseModal(); if (target.dataset.buy) buyModal(state.shopping.find((item) => item.id === target.dataset.buy)); if (target.dataset.edit) expenseModal(state.expenses.find((expense) => expense.id === target.dataset.edit)); if (target.dataset.delete) { const expense = state.expenses.find((entry) => entry.id === target.dataset.delete); if (confirm(`Delete “${expense.name}”?`)) refresh(await api.deleteExpense(expense.id), 'Expense deleted'); } if (target.dataset.settle) { const [from, to] = target.dataset.settle.split(':'); refresh(await api.settleDebt({ from, to }), 'Debt marked as settled'); } if (target.dataset.copy) { await navigator.clipboard?.writeText(target.dataset.copy); toast('Invite link copied'); } });
document.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const values = new FormData(form); try { if (form.id === 'add-item-form') await refresh(await api.addShoppingItem(values.get('name')), 'Added to the shopping list'); if (form.id === 'buy-form') await refresh(await api.buyShoppingItem({ itemId: form.dataset.id, amount: values.get('amount') }), 'Purchase added as a shared expense'); if (form.id === 'expense-form') { const participants = values.getAll('participants'); if (!participants.length) throw new Error('Choose at least one person to split with'); const fields = { name: values.get('name'), amount: values.get('amount'), participants }; await refresh(form.dataset.id ? await api.updateExpense(form.dataset.id, fields) : await api.addExpense(fields), form.dataset.id ? 'Expense updated' : 'Expense added'); } } catch (error) { toast(error.message); } });

state = await api.getState();
render();
